import { motion } from 'motion/react';
import React, { useState, useEffect } from 'react';
import TypewriterText from '../components/Common/TypewriterText';
import { collection, onSnapshot } from 'firebase/firestore';
import { db } from '../lib/firebase';

interface Insight {
  id: string;
  category: string;
  date: string;
  title: string;
  description: string;
  readTime: string;
  image: string;
  content?: string;
  link?: string;
}

const ESSAY_AUTHENTICITY_CONTENT = `### The Inflation of Content and Deflation of Meaning

We are living through a singular moment in human creative history—an era of unprecedented synthetic abundance. The proliferation of generative model architectures has turned the act of producing text, images, and brand frameworks into an operation of near-zero marginal cost. What once required weeks of painstaking, strategic introspection and manual illustration can now be generated by a simple prompt in seconds.

But in this rush toward absolute efficiency, an economic and psychological reality is being overlooked: when anything can be produced instantly, the value of that asset deflates to zero.

When average brands are built on synthetic templates, template patterns begin to saturate the marketplace. Audiences, possessing an evolutionary radar for authenticity, quickly develop an immunity to this synthetic sheen. They feel the lack of weight, the lack of friction, and the absolute absence of a creator's commitment behind the screen. 

In this new landscape, genuine human depth, strategic intentionality, and deliberate, slow craft are no longer luxury choices; they are the ultimate assets of brand survival.

> "In a world of infinite simulated answers, the only true scarcity is the human question—the costly, frictional commitment to taste."

### The Fallacy of Automated Speed

The dominant narrative promoted by modern technology providers is that of "speed-to-market." The goal is to design, deploy, and scale with minimal friction. However, this relies on a deeply flawed assumption: that a brand is merely a functional interface, a set of pipelines designed to deliver utility.

A brand is not a pipeline. A brand is a relational container. 

Relational weight is established through investment. If a brand costs its creator nothing in time, soul, or cognitive focus, it communicates that low investment to its prospective community. By avoiding the friction of genuine thinking, studios and companies are building hollow brands that vanish from collective memory as quickly as they were compiled.

At Sannvara, we believe that design friction is not a bug to be ironed out; it is the source of artistic gravity. The hours spent debating a corner radius, analyzing the historical weight of a typeface like Playfair Display, or manually calibrating typographic kerning on a viewport are what imprints human intentionality onto a brand. 

This human presence cannot be simulated, and it cannot be automated.

---

### Redefining the Creative Imperatives

To build a brand that endures in an automated world, creators and design studios must commit to a new set of baseline tenets:

*   **1. Primary Architectural Custody**
    Brand visual patterns must never be derived from iterative cycles of midjourney prompts. They must originate from a deep, foundational narrative—a conceptual consensus arrived at through dialogue, research, and authentic intuition.
*   **2. Obsessive Typography**
    Typography is the skeletal frame of thought. We select fonts that convey historical lineage and deliberate craftsmanship rather than cold corporate layouts. Every character should carry physical weight and presence.
*   **3. The Unreasonable Attention to Detail**
    Whether it is the responsive timing of a digital card, the subtle parallax shadow of an empty frame, or how clean margins breathe with spacious, intentional negative space—every micro-moment must be obsessively customized.

### Beyond the Automated Grid

The future of digital design does not belong to standard, automated grid systems that look like every other landing page. The future belongs to editorial spaces where art, literature, and technology intersect. 

At Sannvara, we view our client interactions not as transactional agreements but as a mutual pursuit of design integrity. By unlinking ourselves from the demand for hyper-accelerated content production, we dedicate our focus to the slow, meticulous creation of digital objects that stand independent of algorithms.

True luxury is deliberate silence in a world of automated chatter. True brand equity is human commitment.`;

const INSIGHTS: Insight[] = [
  {
    id: 'building-authentic-brand-ai',
    category: 'ESSAY',
    date: 'June 09, 2026',
    title: 'Building an authentic brand in the age of AI',
    description: 'An exploration of why human-centered depth, strategic intentionality, and deliberate craft are more critical than ever in an era saturated with synthetic generation.',
    readTime: '8 MIN READ',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1200',
    content: ESSAY_AUTHENTICITY_CONTENT
  }
];

export default function Gather() {
  const [activeCategory, setActiveCategory] = useState('ALL');
  const [activeInsight, setActiveInsight] = useState<Insight | null>(null);
  const [scrollProgress, setScrollProgress] = useState(0);

  const [email, setEmail] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  const handleSubscribe = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email) return;
    setIsSubmitting(true);
    setErrorMessage('');
    
    try {
      const response = await fetch('/api/subscribe', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ email }),
      });
      
      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || 'Failed to subscribe');
      }
      
      setIsSubmitting(false);
      setIsSubmitted(true);
      setEmail('');
      
      setTimeout(() => {
        setIsSubmitted(false);
      }, 5000);
    } catch (error: any) {
      console.error(error);
      setIsSubmitting(false);
      setErrorMessage(error.message || 'Failed to subscribe. Please try again.');
    }
  };

  const categories = [
    { label: 'ALL', value: 'ALL' },
    { label: 'ESSAYS', value: 'ESSAY' },
    { label: 'NEWSLETTERS', value: 'NEWSLETTER' },
    { label: 'DESIGN DOCUMENTATION', value: 'DOCUMENTATION' },
    { label: 'CULTURAL OBSERVATIONS', value: 'CULTURE' },
    { label: 'PRACTICAL GUIDES', value: 'GUIDE' },
  ];

  const [firebaseInsights, setFirebaseInsights] = useState<Insight[]>([]);

  useEffect(() => {
    const unsub = onSnapshot(collection(db, 'insights'), (snapshot) => {
      const insights = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as Insight));
      setFirebaseInsights(insights);
    });
    
    return () => unsub();
  }, []);

  useEffect(() => {
    if (!activeInsight) {
      setScrollProgress(0);
      return;
    }
    const handleScroll = () => {
      const totalHeight = document.documentElement.scrollHeight - window.innerHeight;
      if (totalHeight > 0) {
        const progress = (window.scrollY / totalHeight) * 100;
        setScrollProgress(progress);
      }
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, [activeInsight]);

  const ALL_INSIGHTS = [...firebaseInsights, ...INSIGHTS];

  const filteredInsights = activeCategory === 'ALL' 
    ? ALL_INSIGHTS 
    : ALL_INSIGHTS.filter(insight => insight.category === activeCategory);

  const handleOpenInsight = (insight: Insight) => {
    setActiveInsight(insight);
    window.scrollTo({ top: 0, behavior: 'instant' as any });
  };

  const handleCloseInsight = () => {
    setActiveInsight(null);
    window.scrollTo({ top: 0, behavior: 'instant' as any });
  };

  // Helper parser for custom blocks inside essay contents
  const renderInsightContent = (contentStr: string | undefined, defaultDesc: string) => {
    const textToParse = contentStr || defaultDesc;
    if (!textToParse) return null;

    const rawParagraphs = textToParse.split('\n\n');
    let paragraphCounter = 0;

    const parsedBlocks = rawParagraphs.map((par, i) => {
      const trimmed = par.trim();
      if (!trimmed) return null;

      if (trimmed.startsWith('### ')) {
        return {
          type: 'header',
          text: trimmed.replace('### ', ''),
          key: `header-${i}`
        };
      } else if (trimmed.startsWith('> "') && trimmed.endsWith('"')) {
        return {
          type: 'blockquote',
          text: trimmed.slice(3, -1),
          key: `quote-${i}`
        };
      } else if (trimmed.startsWith('> ')) {
        return {
          type: 'blockquote',
          text: trimmed.replace(/^>\s*/, ''),
          key: `quote-${i}`
        };
      } else if (trimmed.startsWith('---')) {
        return {
          type: 'divider',
          key: `divider-${i}`
        };
      } else if (trimmed.includes('\n* ') || trimmed.startsWith('* ')) {
        const items = trimmed.split('\n').map(li => li.replace(/^\*\s*/, '').trim()).filter(Boolean);
        return {
          type: 'list',
          items,
          key: `list-${i}`
        };
      } else {
        const currentParIndex = paragraphCounter;
        paragraphCounter++;
        return {
          type: 'paragraph',
          text: trimmed,
          index: currentParIndex,
          key: `p-${i}`
        };
      }
    }).filter(Boolean);

    return (
      <div className="space-y-8">
        {parsedBlocks.map((block: any) => {
          if (block.type === 'header') {
            return (
              <h3 key={block.key} className="text-[25px] md:text-[32px] font-display text-bg-light tracking-tight pt-8 pb-1 font-medium leading-tight">
                {block.text}
              </h3>
            );
          }
          if (block.type === 'blockquote') {
            return (
              <div key={block.key} className="my-12 py-2 text-center">
                <p className="font-display italic text-[21px] md:text-[24px] text-accent/95 leading-relaxed font-normal max-w-[620px] mx-auto">
                  “{block.text}”
                </p>
              </div>
            );
          }
          if (block.type === 'divider') {
            return (
              <hr key={block.key} className="my-14 border-t border-white/10 w-24 mx-auto" />
            );
          }
          if (block.type === 'list') {
            return (
              <ul key={block.key} className="space-y-4 my-6 pl-2">
                {block.items.map((item: string, idx: number) => {
                  const parts = item.split('**');
                  if (parts.length >= 3) {
                    return (
                      <li key={idx} className="flex gap-4 text-bg-light/80 text-[15px] md:text-[16px] leading-relaxed font-body">
                        <span className="text-accent font-serif pr-1 font-bold">•</span>
                        <span>
                          <strong className="text-bg-light font-medium">{parts[1]}</strong>
                          {parts.slice(2).join('')}
                        </span>
                      </li>
                    );
                  }
                  return (
                    <li key={idx} className="flex gap-4 text-bg-light/80 text-[15px] md:text-[16px] leading-relaxed font-body">
                      <span className="text-accent font-serif pr-1 font-bold">•</span>
                      <span>{item}</span>
                    </li>
                  );
                })}
              </ul>
            );
          }
          if (block.type === 'paragraph') {
            return (
              <p key={block.key} className="text-bg-light/75 text-[15px] md:text-[17px] leading-[1.85] font-body font-normal tracking-wide text-justify sm:text-left">
                {block.index === 0 ? (
                  <>
                    <span className="float-left text-[58px] md:text-[70px] font-display font-medium text-accent leading-[0.85] pt-1 pr-3 select-none">
                      {block.text.charAt(0)}
                    </span>
                    {block.text.slice(1)}
                  </>
                ) : (
                  block.text
                )}
              </p>
            );
          }
          return null;
        })}
      </div>
    );
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="pt-40 pb-32 bg-bg-dark min-h-screen text-bg-light"
    >
      {/* Article Detail View / Reader */}
      {activeInsight ? (
        <div className="max-w-[1440px] mx-auto px-5 md:px-[80px]">
          {/* Progress bar tracker */}
          <div className="fixed top-0 left-0 w-full h-[2px] bg-white/5 z-[110]">
            <div 
              className="h-full bg-accent transition-all duration-75" 
              style={{ width: `${scrollProgress}%` }}
            />
          </div>

          {/* Editorial Article Layout */}
          <article className="max-w-[760px] mx-auto pt-8">
            
            {/* Header info */}
            <div className="space-y-6 text-center md:text-left">
              <div className="flex flex-wrap justify-center md:justify-start items-center gap-4 text-[11px] font-mono tracking-widest text-bg-light/40 uppercase">
                <span>{activeInsight.date}</span>
                <span className="text-accent/40">•</span>
                <span>{activeInsight.readTime}</span>
              </div>
              <h1 className="text-[38px] sm:text-[52px] md:text-[68px] leading-[1.1] font-display text-bg-light tracking-tight font-normal">
                {activeInsight.title}
              </h1>
              <p className="text-[16px] md:text-[18px] leading-relaxed text-bg-light/50 font-body max-w-[640px] italic">
                {activeInsight.description}
              </p>
            </div>

            {/* Featured Hero Banner inside Reader */}
            <div className="w-full aspect-[16/9] overflow-hidden rounded-md border border-white/5 bg-white/[0.02] my-12 shadow-xl">
              <img 
                src={activeInsight.image} 
                alt={activeInsight.title}
                className="w-full h-full object-cover"
                referrerPolicy="no-referrer"
              />
            </div>

            {/* Beautiful Body Essay Content */}
            <div className="pt-2 pb-24">
              {renderInsightContent(activeInsight.content, activeInsight.description)}
            </div>

            {/* In-app reading completion footer */}
            <div className="pt-12 text-center pb-12">
              <button 
                onClick={handleCloseInsight}
                className="inline-block px-8 py-3.5 bg-transparent border border-white/20 hover:border-accent hover:text-accent font-mono text-[11px] tracking-widest uppercase transition-all duration-300 rounded-[8px]"
              >
                Return to the Gather
              </button>
            </div>

          </article>
        </div>
      ) : (
        /* Original Listings Grid View */
        <div className="max-w-[1440px] mx-auto px-5 md:px-[80px]">
          {/* Header Section */}
          <div className="pb-16 mb-8 md:mb-16">
            <h1 className="text-[64px] md:text-[96px] leading-[1.05] tracking-tight text-bg-light font-display">
              <TypewriterText text="The Gather" />
            </h1>
            <p className="text-[18px] text-bg-light/55 max-w-[600px] mt-6 leading-relaxed font-body font-normal">
              A repository of strategic discourse, design documentation, and cultural observations. Edited and published periodically by Sannvara.
            </p>
          </div>

          {/* Navigation Filter */}
          <div className="flex overflow-x-auto no-scrollbar gap-8 md:gap-14 border-b border-bg-light/10 mb-16">
            {categories.map((category) => (
              <button
                key={category.value}
                onClick={() => setActiveCategory(category.value)}
                className={`whitespace-nowrap transition-colors duration-300 pb-4 relative text-[12px] md:text-[13px] font-mono tracking-widest uppercase ${
                  activeCategory === category.value
                    ? 'text-accent font-bold'
                    : 'text-bg-light/40 hover:text-bg-light/80'
                }`}
              >
                {category.label}
                {activeCategory === category.value && (
                  <span className="absolute bottom-[-1px] left-0 w-full h-[1px] bg-accent" />
                )}
              </button>
            ))}
          </div>

          {/* Insights Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-x-16 gap-y-24">
            {filteredInsights.map((insight, index) => (
              <motion.article
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ delay: index * 0.1, duration: 0.6 }}
                key={insight.id}
                onClick={() => handleOpenInsight(insight)}
                className="group cursor-pointer pb-12 transition-colors duration-500"
              >
                <div className="aspect-[4/3] w-full mb-8 overflow-hidden rounded-sm bg-white/[0.01] border border-white/5">
                  <img 
                    src={insight.image} 
                    alt={insight.title}
                    className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                    referrerPolicy="no-referrer"
                  />
                </div>

                <div className="flex justify-between items-center text-[11px] font-mono tracking-widest text-bg-light/40 uppercase mb-6">
                  <span className="text-accent/80 font-bold">{insight.category}</span>
                  <div className="flex gap-4">
                    <span>{insight.date}</span>
                    <span className="text-bg-light/20">•</span>
                    <span>{insight.readTime}</span>
                  </div>
                </div>

                <h2 className="text-[32px] md:text-[40px] leading-[1.2] font-display text-bg-light group-hover:text-accent transition-colors duration-300 mb-4 font-normal">
                  {insight.title}
                </h2>

                <p className="text-[15px] leading-relaxed text-bg-light/55 font-body font-normal max-w-[540px]">
                  {insight.description}
                </p>

                <div className="mt-8 flex items-center gap-2 text-[11px] font-mono tracking-widest uppercase text-bg-light/35 group-hover:text-accent transition-colors duration-300">
                  <span>Read Insight</span>
                  <span className="transform translate-x-0 group-hover:translate-x-1.5 transition-transform duration-300">→</span>
                </div>
              </motion.article>
            ))}
          </div>

          {/* Newsletter Section */}
          <div className="mt-32 pt-24 border-t border-bg-light/10 flex flex-col lg:flex-row justify-between items-start lg:items-center gap-12">
            <div className="max-w-[540px]">
              <h2 className="text-[36px] md:text-[44px] leading-tight font-display text-bg-light mb-4">
                Stay in The Gather.
              </h2>
              <p className="text-[15px] md:text-[17px] leading-relaxed text-bg-light/55 font-body">
                Strategic discourse and cultural observations, delivered periodically. No noise. Only what holds.
              </p>
            </div>
            <div className="w-full lg:w-auto">
              <form onSubmit={handleSubscribe} className="flex flex-col sm:flex-row gap-0 w-full">
                <input 
                  type="email" 
                  required
                  disabled={isSubmitting || isSubmitted}
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder={isSubmitted ? "You are subscribed" : "Your email address"}
                  className="bg-bg-light/5 text-bg-light font-body text-[15px] px-6 py-5 sm:min-w-[320px] focus:outline-none focus:ring-1 focus:ring-accent transition-all placeholder:text-bg-light/30 border border-transparent focus:border-accent/30 disabled:opacity-50"
                />
                <button 
                  type="submit"
                  disabled={isSubmitting || isSubmitted}
                  className={`font-mono text-[11px] md:text-[12px] font-bold tracking-[0.15em] px-10 py-5 transition-colors duration-300 ${
                    isSubmitted 
                      ? 'bg-accent text-bg-dark font-black' 
                      : isSubmitting 
                        ? 'bg-accent/40 text-bg-dark/50 cursor-not-allowed' 
                        : 'bg-accent text-bg-dark hover:bg-white'
                  }`}
                >
                  {isSubmitted ? 'subscribed' : isSubmitting ? 'subscribing...' : 'subscribe'}
                </button>
              </form>
              {errorMessage && (
                <p className="text-red-500 text-[12px] font-mono mt-2">{errorMessage}</p>
              )}
            </div>
          </div>
        </div>
      )}
    </motion.div>
  );
}
